# Generated by Django 4.2.16 on 2024-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.AlterField(
            model_name='movpost',
            name='cinema',
            field=models.ManyToManyField(blank=True, to='posts.platform'),
        ),
    ]
