# Generated by Django 4.2.16 on 2024-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_platform_delete_cinema_alter_movpost_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movpost',
            old_name='cinema',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='movpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movpost',
            name='mov_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movpost',
            name='time',
            field=models.TimeField(),
        ),
    ]
